#!/bin/sh

APP_SVC='APPLICATION_PACKAGE.service'
LOG_DIR=/var/log/APPLICATION_PACKAGE
TMP_DIR=/tmp/APPLICATION_PACKAGE

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


echo "Handling '$1' from $0"

if [ "$1" = "remove" ]; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
	fi

	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask $APP_SVC >/dev/null || true
	fi
fi

if [ "$1" = "purge" ] ; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge $APP_SVC >/dev/null || true
		deb-systemd-helper unmask $APP_SVC >/dev/null || true
	fi

	if [ -z "${DPKG_ROOT:-}" ]; then
		update-rc.d APPLICATION_PACKAGE remove >/dev/null
	fi

	for i in $LOG_DIR $TMP_DIR; do
		if dpkg-statoverride --list $i >/dev/null 2>&1; then
			dpkg-statoverride --remove $i
		fi
	done
	
	for i in $LOG_DIR $TMP_DIR; do
		[ -d $i ] && rm -rf $i
	done
	
fi

if [ "$1" = "upgrade" ]; then
	echo "Not doing anything for 'upgrade'"
fi

#case "$1" in
#    upgrade|failed-upgrade|abort-upgrade)
#		deb-systemd-helper start 'APPLICATION_PACKAGE.service' || true
#    ;;
#
#    purge|remove|abort-install|disappear)
#    	[ -f /usr/lib/systemd/system/APPLICATION_PACKAGE.service ] && rm /usr/lib/systemd/system/APPLICATION_PACKAGE.service
#    	
#    	for i in /opt/APPLICATION_PACKAGE; do
#		    if dpkg-statoverride --list $i >/dev/null 2>&1; then
#		        dpkg-statoverride --remove $i
#		    fi
#		done
#    ;;

#    *)
#        echo "postrm called with unknown argument \`$1'" >&2
#        exit 1
#    ;;
#esac

#exit 0