#!/bin/sh

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


echo "Handling $1 in prem"

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
	systemctl stop 'APPLICATION_PACKAGE.service' || true
fi

if [ "$1" = "remove" ] && [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop 'APPLICATION_PACKAGE.service' >/dev/null || true
fi

#case "$1" in
#    upgrade)
#		deb-systemd-helper stop 'APPLICATION_PACKAGE.service' || true
#    ;;
#
#    remove|deconfigure)
#		deb-systemd-helper stop 'APPLICATION_PACKAGE.service' || true
#		deb-systemd-helper disable 'APPLICATION_PACKAGE.service' || true
#    ;;
#
#    failed-upgrade)
#    ;;
#
#    *)
#        echo "prerm called with unknown argument \`$1'" >&2
#        exit 1
#    ;;
#esac

exit 0
