#!/bin/sh

APP_SVC=APPLICATION_PACKAGE.service
set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


echo "Handling $1 from $0"

if [ "$1" = "remove" ]; then
	if [ -d /run/systemd/system ]; then
		systemctl stop 'APPLICATION_PACKAGE.service' || true
	fi

	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
		deb-systemd-invoke stop 'APPLICATION_PACKAGE.service' >/dev/null || true
	fi

	if [ -z "${DPKG_ROOT:-}" ] && [ -x /etc/init.d/APPLICATION_PACKAGE ]; then
		invoke-rd.d --skip-systemd-native $APPLICATION_PACKAGE stop || true
	fi
fi

exit 0
